# Generated by Django 3.0 on 2019-12-29 23:56

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0002_auto_20191223_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerBoarder',
            fields=[
                ('BOARD_NUM', models.BigAutoField(primary_key=True, serialize=False)),
                ('BOARD_NAME', models.CharField(max_length=20)),
                ('BOARD_PASS', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(8, '8자 이상이어야 합니다.')])),
                ('BOARD_SUBJECT', models.CharField(max_length=50)),
                ('BOARD_CONTENT', models.CharField(blank=True, max_length=2000, null=True)),
                ('BOARD_RE_REF', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('BOARD_RE_LEV', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('BOARD_RE_SEQ', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('BOARD_READCOUNT', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('BOARD_DATE', models.DateTimeField(default=datetime.datetime.now)),
                ('BOARD_ORIGINAL_FILENAME', models.CharField(blank=True, max_length=500, null=True)),
                ('BOARD_STORE_FILENAME', models.FileField(blank=True, max_length=500, null=True, upload_to='uploads/')),
                ('BOARD_FILE_SIZE', models.CharField(blank=True, max_length=200, null=True)),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'db_table': 'ANSWERBOARDER',
            },
        ),
    ]
