# Generated by Django 3.0 on 2019-12-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answerBoarder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerboarder',
            name='BOARD_STORE_FILENAME',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
