# Generated by Django 3.0 on 2019-12-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('USER_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('USER_PW', models.CharField(max_length=100)),
                ('USER_NAME', models.CharField(max_length=20)),
                ('USER_BIRTH', models.DateTimeField()),
                ('USER_GENDER', models.CharField(max_length=1)),
                ('USER_EMAIL', models.CharField(max_length=50)),
                ('USER_ADDR', models.CharField(max_length=100)),
                ('USER_PH1', models.CharField(max_length=13)),
                ('USER_PH2', models.CharField(blank=True, max_length=13, null=True)),
                ('USER_REGIST', models.DateTimeField()),
                ('USER_CK', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
