# Generated by Django 3.0 on 2019-12-23 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='USER_PH1',
            field=models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(12, '길이가 너무 짧습니다.')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='USER_PW',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(8, '8자 이상이어야 합니다.')]),
        ),
    ]
